.PHONY: build test clean

build:
	@echo "Building tree builder..."
	cargo build --release

test:
	@echo "Running tree builder tests..."
	cargo test

clean:
	@echo "Cleaning tree builder..."
	cargo clean
