.PHONY: build test clean run

build:
	@echo "Building relayer..."
	cargo build --release

test:
	@echo "Running relayer tests..."
	cargo test

run:
	@echo "Starting relayer..."
	cargo run --release

clean:
	@echo "Cleaning relayer..."
	cargo clean
